import type { AffinityResult, FactorRef, SlotFactor } from "../api";
import { APTITUDE_LABELS } from "../aptitude";
import {
  NAMED_COUNT,
  NAMED_SHORT,
  affinitySlotOf,
  sparkAt,
  type Design,
} from "../blueprint";
import {
  combineOutlooks,
  formatChance,
  memberSparks,
  sparkId,
  type SparkRef,
} from "../procs";
import { SparkEditor } from "./SparkEditor";

// The Procs tab. Every spark in the tree is here as a chance the TRAINEE
// comes out with it — which is what an inspiration proc off an ancestor is.
// See procs.ts for the model and why every number is an estimate.

// A spark's display name. Everything but the pink is resolved from the
// committed reference at render time rather than stored with the design:
// names are localized strings and the factor key is the identity. A key the
// reference doesn't know (it is regenerated by hand, so it can run behind a
// dump) degrades to the same "Unknown (key)" the decoder uses, instead of
// rendering blank.
function sparkName(ref: SparkRef, names: Map<string, string>): string {
  return ref.type === "pink"
    ? APTITUDE_LABELS[ref.aptitude]
    : (names.get(sparkId(ref)) ?? `Unknown (${ref.key})`);
}

const Stars = ({ n }: { n: number }) => <span className="proc-stars">{"★".repeat(n)}</span>;

// The chance, as a bar filled in the spark's own colour with the number
// riding on it.
//
// Scaled 0–100 absolutely, not to the table's own maximum. A relative scale
// would rank the rows more legibly, but it would also draw a full bar for a
// 3% spark whenever nothing else beats it — and "unlikely" is exactly what
// this table exists to tell you. The realistic range does use the space: a 3★
// green on a well-matched parent runs past 80%, a 1★ race sits near 3%.
const ChanceBar = ({ type, chance }: { type: SparkRef["type"]; chance: number | null }) =>
  chance === null ? (
    <span className="proc-none">—</span>
  ) : (
    <div className="proc-bar">
      <div className={`proc-fill proc-fill-${type}`} style={{ width: `${chance}%` }} />
      <span className="proc-pct">{formatChance(chance)}</span>
    </div>
  );

// Both tables label the numbers the same way: "est." because the rates were
// never datamined, "per run" because this is the chance over the whole
// career's two compatibility-dependent inheritance events, not the chance at
// any one of them.
const ChanceHeader = () => (
  <th
    scope="col"
    className="proc-chance"
    title="Estimated, not datamined — chance over the run's two inheritance events"
  >
    Est. per run
  </th>
);

// One row: the spark named in its kind's colour, and the chance beside it in
// a bar filled to match. The kind is carried by colour alone — a spelled-out
// tag said the same thing a third time and cost the names the width they
// need. The search list in SparkEditor keeps its tags, where you are choosing
// between kinds rather than reading your own.
const SparkRow = ({
  spark,
  name,
}: {
  spark: SparkRef & { stars: number; chance: number | null };
  name: string;
}) => (
  <tr className={`proc-row proc-row-${spark.type}`}>
    <td className="proc-name">
      {name} <Stars n={spark.stars} />
    </td>
    <td className="proc-chance">
      <ChanceBar type={spark.type} chance={spark.chance} />
    </td>
  </tr>
);

// One ancestor's own sparks: what each is worth as a contribution to the
// trainee, at this member's individual affinity (DECISIONS.md #29). Her pink
// leads, then everything else strongest first.
export function NodeProcs({
  design,
  affinity,
  index,
  sparkNames,
  factorRefs,
  locked,
  onSetFactors,
}: {
  design: Design;
  affinity: AffinityResult | null;
  index: number;
  sparkNames: Map<string, string>;
  factorRefs: FactorRef[];
  // Inside a pulled branch: these sparks are the horse's own, read off her
  // dump, so they are shown rather than edited — the same rule her pink
  // follows.
  locked: boolean;
  onSetFactors: (i: number, factors: SlotFactor[]) => void;
}) {
  const id = affinitySlotOf(index);
  const share = id === null || affinity === null ? null : affinity[`${id}_affinity`];
  const slot = design.named[index];
  const factors = slot?.factors ?? [];
  const rows = memberSparks(sparkAt(design, index), factors, share);
  return (
    <>
      <table className="proc-table">
        <thead>
          <tr>
            <th scope="col" className="proc-name">Spark</th>
            {/* Said once per table rather than on every value — a column
                header labels every number under it. */}
            <ChanceHeader />
          </tr>
        </thead>
        <tbody>
          {rows.length === 0 ? (
            <tr>
              <td className="proc-name proc-empty" colSpan={2}>
                No sparks on this member yet.
              </td>
            </tr>
          ) : (
            rows.map((r) => (
              <SparkRow key={sparkId(r)} spark={r} name={sparkName(r, sparkNames)} />
            ))
          )}
        </tbody>
      </table>
      {/* The pink is edited on the Details tab, beside the letters it bumps
          at career start; these feed nothing but these numbers, so they are
          entered here. */}
      {!locked && (
        <SparkEditor
          label={NAMED_SHORT[index]}
          factors={factors}
          refs={factorRefs}
          onChange={(next) => onSetFactors(index, next)}
        />
      )}
    </>
  );
}

// The trainee's roll-up: one row per distinct spark in the tree, at the
// chance ANY of its carriers lands it. Two members holding the same skill is
// how you actually hunt one, so the combined number is the one that says
// whether the plan is good enough — and it is the question no single
// ancestor's tab can answer.
export function TraineeProcs({
  design,
  affinity,
  sparkNames,
}: {
  design: Design;
  affinity: AffinityResult | null;
  sparkNames: Map<string, string>;
}) {
  const perMember = [];
  for (let i = 1; i < NAMED_COUNT; i++) {
    const id = affinitySlotOf(i);
    const share = id === null || affinity === null ? null : affinity[`${id}_affinity`];
    const slot = design.named[i];
    const sparks = memberSparks(sparkAt(design, i), slot?.factors ?? [], share);
    if (sparks.length > 0) perMember.push({ index: i, sparks });
  }
  const outlooks = combineOutlooks(perMember);
  if (outlooks.length === 0) {
    return <p className="focus-note">No sparks on the ancestors yet.</p>;
  }
  return (
    <table className="proc-table">
      <thead>
        <tr>
          <th scope="col" className="proc-name">Spark</th>
          <ChanceHeader />
        </tr>
      </thead>
      <tbody>
        {/* Which members carry each spark is deliberately not a column: this
            table answers "what am I likely to come out with", and the
            per-member breakdown is one click away on their own tabs. */}
        {outlooks.map((o) => (
          <SparkRow key={sparkId(o)} spark={o} name={sparkName(o, sparkNames)} />
        ))}
      </tbody>
    </table>
  );
}
