import { useEffect, useState } from "react";
import {
  ApiError,
  SLOT_FACTOR_KINDS,
  type FactorRef,
  type SlotFactor,
  type SlotFactorKind,
  type SparkList,
  type SparkRef,
} from "../api";
import { deriveCharaId } from "../blueprint";
import { SPARK_TYPE_LABELS, SPARK_TYPE_ORDER, sparkId } from "../procs";
import {
  createListWith,
  favorites as unionOf,
  listsWith,
  PartialWrite,
  toggleMembership,
  type SparkListStore,
} from "../sparks";

// Hand entry for a member's non-pink sparks: a popout that BROWSES the 437
// factors, with the ones you've favorited at the top (DECISIONS.md #35).
//
// ADDING is all it does, and adding includes the LEVEL — three buttons per
// row, so a 3★ is one click at the moment you are choosing the spark
// (DECISIONS.md #34). Nothing here can change a chance in the table behind it.
//
// FAVOURITING is a different act from adding, deliberately: a filler white you
// type onto every node must not land in #27's watched block, and a row must
// not move under the pointer that just clicked it.
//
// The ★ OPENS A LIST PICKER rather than toggling one flag (DECISIONS.md #37).
// A favorite is a spark in at least one of the user's named lists, so "star
// this" has to say WHICH list — and with several lists active at once, "the
// active one" names nothing unambiguous. The picker doubles as the membership
// editor, and `New List` lives in it so a user with no lists needs no separate
// settings surface.
//
// A roster or lineage pick never needs any of this — hers are decoded from the
// dump — so it only appears on hand-built nodes, and never inside a locked
// branch.

// The browse sections, in the order the spark tables group by (procs.ts),
// minus the pink the document doesn't hand-enter.
const BROWSE_KINDS: SlotFactorKind[] = [...SLOT_FACTOR_KINDS].sort(
  (a, b) => SPARK_TYPE_ORDER[a] - SPARK_TYPE_ORDER[b]
);

// A green spark's factor key IS a card_id — `app/ingest.py` says so in its
// header, the reference agrees (95 of the 97 released cards have a unique
// factor at their own id), and a real roster agrees at n=1372: every veteran
// and lineage member carries at most ONE green, and it is always her own card.
// A uma can LEARN another uma's unique during a run; she can never carry the
// spark for one.
//
// So the green a node can hold is decided by who is cast in it. One rule,
// three tiers (DECISIONS.md #36):
//
//   card known      → her card's unique, which is one row or none
//   chara only      → that character's 1–3 variants
//   neither         → all 137, each named with the uma it belongs to
//
// The middle tier covers a slot carrying `chara_id` without `card_id`: the
// picker always sets both, but the type allows it. Only `unique` is
// card-bound — pink, race, white and scenario belong to anyone.
const greenFilter =
  (cardId: number | null, charaId: number | null) =>
  (option: Option): boolean => {
    if (option.kind !== "unique") return true;
    if (cardId !== null) return option.key === cardId;
    if (charaId !== null) return deriveCharaId(option.key) === charaId;
    return true;
  };

// A row the chooser can offer: a spark from the reference, or one the
// reference doesn't know. List membership is deliberately not validated
// against `app/data` (#37) — the reference is regenerated by hand and can run
// behind a dump — so a favorite may resolve to no name and still be addable.
type Option = { kind: SlotFactorKind; key: number; name: string };

const optionOf = (ref: FactorRef): Option => ref;

const unknownOption = (spark: SparkRef): Option => ({
  kind: spark.kind,
  key: spark.key,
  // The same degradation ProcPanel uses for a stored spark the reference
  // can't name, rather than a blank row.
  name: `Unknown (${spark.key})`,
});

/**
 * The membership editor for one spark: every list, checked where it holds it,
 * plus a field that makes a new one.
 *
 * Rendered UNDER the row rather than as a nested dialog — the popout is 358px
 * on a 390px phone, the row already carries a ★, a kind tag, a name and three
 * add buttons, and a dialog inside a dialog is a focus-trap problem for a
 * control this small.
 *
 * With no lists at all this is just the field, which is the zero-list first
 * run and the only place `New List` needs to exist.
 */
function ListPicker({
  lists,
  kind,
  factorKey,
  name,
  busy,
  listsFailed,
  onToggleList,
  onCreateList,
}: {
  lists: SparkList[];
  kind: SlotFactorKind;
  factorKey: number;
  name: string;
  busy: boolean;
  // The ★ that discloses this picker is disabled when the lists failed to
  // load; without the same guard here, an ALREADY-OPEN picker stays writable
  // after the app has proven its copy stale — and a pill click then PATCHes
  // the whole membership array built from that stale copy, silently dropping
  // anything another device added.
  listsFailed: boolean;
  onToggleList: (listId: number) => void;
  // Resolves false when the server refused the name, which is when the field
  // must keep it.
  onCreateList: (listName: string) => Promise<boolean>;
}) {
  const [draft, setDraft] = useState("");
  // Cleared only once the list exists, so correcting a name collision doesn't
  // mean retyping it from scratch.
  const submit = () => {
    const trimmed = draft.trim();
    if (trimmed === "") return;
    void onCreateList(trimmed).then((made) => {
      if (made) setDraft("");
    });
  };
  return (
    <div className="spark-lists" role="group" aria-label={`Lists for ${name}`}>
      {lists.map((list) => {
        const holds = list.sparks.some(
          (s) => s.kind === kind && s.key === factorKey
        );
        return (
          <button
            key={list.id}
            className={holds ? "spark-list-pill active" : "spark-list-pill"}
            aria-pressed={holds}
            // Both identities on the control: anything driving this by
            // displayed name would have to disambiguate two lists whose names
            // differ only in case, and two whites both called "Pressure".
            data-list={list.id}
            data-spark={sparkId({ type: kind, key: factorKey })}
            // Names the OUTCOME, not the list: a chip labelled with a name
            // alone reads as a tag rather than a control.
            aria-label={
              holds
                ? `Remove ${name} from ${list.name}`
                : `Add ${name} to ${list.name}`
            }
            title={holds ? `Remove from ${list.name}` : `Add to ${list.name}`}
            disabled={busy || listsFailed}
            onClick={() => onToggleList(list.id)}
          >
            {list.name}
            {/* A glyph inside the button, never a nested one — a button in a
                button is invalid, and two hit targets for one action is a miss
                waiting to happen at 358px. */}
            <span className="spark-list-mark" aria-hidden="true">
              {holds ? "✕" : "+"}
            </span>
          </button>
        );
      })}
      <span className="spark-list-new">
        <input
          className="uma-search"
          type="text"
          aria-label={`New list for ${name}`}
          placeholder="New List…"
          // Matches `SparkListName`'s bound, so the limit is felt as the field
          // refusing a 41st character rather than as a save that fails after.
          // The server still enforces it.
          maxLength={40}
          value={draft}
          disabled={busy || listsFailed}
          onChange={(e) => setDraft(e.target.value)}
          // `isComposing` guards the IME: confirming a candidate in Japanese
          // input is an Enter keydown too, and acting on it would create a list
          // named with the pre-conversion kana — permanently, since nothing
          // renames or deletes one yet.
          onKeyDown={(e) => {
            if (e.key === "Enter" && !e.nativeEvent.isComposing) {
              e.preventDefault();
              submit();
            }
          }}
        />
        <button
          className="spark-list-add"
          aria-label={`Create list for ${name}`}
          disabled={busy || listsFailed || draft.trim() === ""}
          onClick={submit}
        >
          Add
        </button>
      </span>
    </div>
  );
}

function SparkRows({
  options,
  held,
  lists,
  listsFailed,
  busy,
  openPicker,
  cardOwner,
  onAdd,
  onOpenPicker,
  onToggleList,
  onCreateList,
}: {
  options: Option[];
  held: Set<string>;
  lists: SparkList[];
  listsFailed: boolean;
  busy: boolean;
  // Which row's list picker is open, by spark id, or null. One at a time:
  // two open pickers on a 358px popout is most of the surface, and the
  // question each answers is about its own row.
  openPicker: string | null;
  // Names the uma a green belongs to. Only meaningful where the green list
  // is NOT already narrowed to one card — on a cast node the panel above
  // says whose sparks these are.
  cardOwner: (cardId: number) => string | null;
  onAdd: (option: Option, stars: number) => void;
  onOpenPicker: (id: string | null) => void;
  onToggleList: (option: Option, listId: number) => void;
  onCreateList: (option: Option, listName: string) => Promise<boolean>;
}) {
  return (
    <ul className="spark-matches">
      {options.map((o) => {
        const id = sparkId({ type: o.kind, key: o.key });
        const holders = listsWith(lists, o.kind, o.key);
        const fav = holders.length > 0;
        const picking = openPicker === id;
        return (
          <li key={id}>
            {/* Disabled rather than hidden when the lists didn't load, so the
                chooser doesn't silently change shape on a fetch failure. It
                DISCLOSES the picker rather than writing anything: filled means
                "in at least one list", and which list is the question the
                picker below exists to ask. */}
            <button
              className={fav ? "spark-fav active" : "spark-fav"}
              aria-expanded={picking}
              // The identity on the control: the reference holds two distinct
              // whites both called "Pressure", so anything driving this list
              // by displayed name can hit the wrong (kind, key).
              data-spark={id}
              // Names the STATE as well as the control: `aria-expanded`
              // describes the picker below, not membership, so without the
              // count every row announces identically whether or not the spark
              // is in a list.
              aria-label={
                fav
                  ? `Lists for ${o.name} — in ${holders.length} of ${lists.length}`
                  : `Lists for ${o.name} — in none`
              }
              disabled={listsFailed || busy}
              onClick={() => onOpenPicker(picking ? null : id)}
            >
              {fav ? "★" : "☆"}
            </button>
            <span className="spark-hit">
              {/* The kind is part of the identity here — you are picking
                  BETWEEN kinds, and several race and scenario sparks share
                  wording with skills. */}
              <span className={`proc-kind proc-kind-${o.kind}`}>
                {SPARK_TYPE_LABELS[o.kind]}
              </span>
              {o.name}
              {/* Whose green this is — 137 anonymous greens is a list you
                  cannot navigate. Absent for the 42 uniques whose card has not
                  reached Global. */}
              {o.kind === "unique" && cardOwner(o.key) !== null && (
                <span className="spark-owner">{cardOwner(o.key)}</span>
              )}
            </span>
            {held.has(id) ? (
              // Shown, marked, rather than filtered into silence: finding the
              // right name and getting nothing back reads as "no such spark".
              <span className="spark-held">Added</span>
            ) : (
              // Not a `radiogroup`: these three don't hold a value between
              // them, they are three different add actions. Each names its own
              // outcome, because "3★" alone is meaningless read out of the row
              // it sits in.
              <span className="seg-group" role="group">
                {[1, 2, 3].map((n) => (
                  <button
                    key={n}
                    className="seg"
                    data-spark={id}
                    data-stars={n}
                    aria-label={`Add ${o.name} at ${n}★`}
                    onClick={() => onAdd(o, n)}
                  >
                    {n}★
                  </button>
                ))}
              </span>
            )}
            {/* Only for the row whose ★ is open, and on its own line: at 358px
                a fifth control on the line takes the name's width. */}
            {picking && (
              <ListPicker
                lists={lists}
                kind={o.kind}
                factorKey={o.key}
                name={o.name}
                busy={busy}
                listsFailed={listsFailed}
                onToggleList={(listId) => onToggleList(o, listId)}
                onCreateList={(listName) => onCreateList(o, listName)}
              />
            )}
          </li>
        );
      })}
    </ul>
  );
}

function ChooserPopout({
  label,
  factors,
  refs,
  sparkLists,
  cardId,
  charaId,
  cardOwner,
  onAdd,
  onError,
  onClose,
}: {
  label: string;
  factors: readonly SlotFactor[];
  refs: readonly FactorRef[];
  sparkLists: SparkListStore;
  cardId: number | null;
  charaId: number | null;
  cardOwner: (cardId: number) => string | null;
  onAdd: (option: Option, stars: number) => void;
  onError: (message: string) => void;
  onClose: () => void;
}) {
  const [query, setQuery] = useState("");
  const [busy, setBusy] = useState(false);
  const [openPicker, setOpenPicker] = useState<string | null>(null);
  // WHICH sparks sit in the Favorites section, snapshotted for the life of
  // this open. MEMBERSHIP is frozen; the ★ and the picker's pills stay live off
  // the lists. Without the freeze, favoriting a row lifts it out of its kind
  // section and the add buttons you were reaching for move away under the
  // pointer. It has to be MEMBERSHIP rather than `favorited ∩ snapshot`
  // (DECISIONS.md #36): under the intersection, un-starring dropped a row out
  // of Favorites while the frozen set still hid it from its kind section, so
  // the spark left the popout entirely and could not be added until you closed
  // and reopened. Frozen membership makes un-starring empty the star and move
  // nothing.
  //
  // Taken once per mount, and the caller REMOUNTS this popout when the lists
  // settle (see the `key` below) — which keeps the snapshot from freezing an
  // empty union mid-fetch without needing an effect or a ref read at render.
  const [pinnedRows] = useState(() => unionOf(sparkLists.lists));
  const pinned = new Set(pinnedRows.map((w) => sparkId({ type: w.kind, key: w.key })));

  // Escape closes UNCONDITIONALLY, including mid-write: blocking it while
  // `busy` silently swallows the keypress. What that leaves open — close
  // mid-write, reopen, and the fresh popout has `busy` false, so a second
  // whole-array PATCH can be built from state the first hasn't updated yet and
  // land last — is filed rather than guarded.
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onClose]);

  const held = new Set(factors.map((f) => sparkId({ type: f.kind, key: f.key })));
  const names = new Map(
    refs.map((r) => [sparkId({ type: r.kind, key: r.key }), r.name])
  );
  const q = query.trim().toLowerCase();
  // Applied to the favorites too: a green you favorited is still a green this
  // member cannot carry, so pinning it to the top of a node it does not belong
  // to would be the one place the rule leaks.
  const possible = greenFilter(cardId, charaId);
  // One rule for every section: hits rank by where the query lands in the name
  // then alphabetically — a no-op with no query, the reference arriving sorted
  // by (kind, name) already.
  const matching = (options: Option[]): Option[] => {
    const hits = options.filter((o) => possible(o) && o.name.toLowerCase().includes(q));
    if (q === "") return hits;
    return hits.sort(
      (a, b) =>
        a.name.toLowerCase().indexOf(q) - b.name.toLowerCase().indexOf(q) ||
        a.name.localeCompare(b.name)
    );
  };

  // Built from the frozen snapshot, so a row stays put when you un-star it.
  const favorites = matching(
    pinnedRows.map((w) => {
      const name = names.get(sparkId({ type: w.kind, key: w.key }));
      return name === undefined ? unknownOption(w) : { kind: w.kind, key: w.key, name };
    })
  );
  // A favorite is in the Favorites section and NOWHERE ELSE — the same spark
  // twice on one surface reads as "which of these two rows did I already
  // star". The snapshot decides, so nothing disappears from under the pointer.
  const sections = BROWSE_KINDS.map((kind) => ({
    kind,
    options: matching(
      refs
        .filter(
          (r) => r.kind === kind && !pinned.has(sparkId({ type: r.kind, key: r.key }))
        )
        .map(optionOf)
    ),
  })).filter((s) => s.options.length > 0);

  // Non-optimistic: `sparks.ts` returns the list the server ended up with, so
  // the star only moves once the row exists.
  //
  // Failures go to the PAGE toast, not a note inside this popout: dismissing
  // the popout mid-write is one keystroke, and a note that unmounts with its
  // surface reports nothing at all.
  //
  // The message is the CALLER's — the two controls fail differently and this
  // helper serves both — and it takes the error rather than a fixed string,
  // since a 409 from the create is either a name collision or the 50-list cap.
  //
  // Returns whether it wrote, so the new-list field knows to keep the name it
  // was given when the server refused it.
  const write = async (
    op: () => Promise<SparkList[]>,
    failure: (error: unknown) => string
  ): Promise<{ ok: true } | { ok: false; error: unknown }> => {
    setBusy(true);
    try {
      sparkLists.onChange(await op());
      return { ok: true };
    } catch (error) {
      // Half of it landed — adopt that half, or the row exists server-side
      // and nowhere on screen. See sparks.ts PartialWrite.
      if (error instanceof PartialWrite) sparkLists.onChange(error.lists);
      // A 404 means the list was deleted elsewhere and this copy is stale. NOT
      // corrected here — a reload bumps `epoch`, which remounts the popout and
      // discards the user's search and open picker. The dead pill survives
      // until the popout is reopened.
      onError(failure(error));
      return { ok: false, error };
    } finally {
      setBusy(false);
    }
  };

  // The server's own words for a refusal it can explain — 409 for the name
  // rules, 422 for everything `app/schemas.py` validates. 422 matters as much
  // as 409: without it an over-long name reports "try again" forever, a
  // permanent refusal phrased as a transient one. Anything else is a blip.
  const detailOr = (error: unknown, fallback: string): string =>
    error instanceof ApiError &&
    (error.status === 409 || error.status === 422) &&
    error.message !== ""
      ? `${error.message.charAt(0).toUpperCase()}${error.message.slice(1)}.`
      : fallback;

  const rowProps = {
    held,
    lists: sparkLists.lists,
    listsFailed: sparkLists.failed,
    busy,
    openPicker,
    // Only worth printing where the green list is still ambiguous — narrowed
    // to one card, the panel above already names her.
    cardOwner: cardId === null ? cardOwner : () => null,
    onAdd,
    onOpenPicker: setOpenPicker,
    onToggleList: (o: Option, listId: number) =>
      void write(
        () => toggleMembership(sparkLists.lists, listId, o.kind, o.key),
        () => "Couldn't save that list change — try again."
      ),
    // Resolves "did the NAME get consumed", which is not the same question as
    // "did the write succeed" — see the PartialWrite case below. The field
    // keeps the typed name until this resolves true, so a name the server
    // refused can be corrected rather than retyped.
    onCreateList: async (o: Option, listName: string) => {
      const result = await write(
        () => createListWith(sparkLists.lists, listName, o.kind, o.key),
        (error) =>
          error instanceof PartialWrite
            ? "Made the list, but couldn't add the spark — click its pill to finish."
            : detailOr(error, "Couldn't make that list — try again.")
      );
      // A PartialWrite means the list EXISTS under that name — only its
      // membership failed — so the name is spent and the field must clear, or
      // the obvious retry POSTs a name that now 409s against it.
      return result.ok || result.error instanceof PartialWrite;
    },
  };

  return (
    <>
      {/* Dismisses on mousedown, not click: Chrome freezes the OS cursor when
          a click unmounts the element under it, which reads as "hover is
          broken" until the next click. The filter panel's popouts do the
          same. */}
      <div className="uma-popout-backdrop" onMouseDown={onClose} />
      <div className="uma-popout spark-popout" role="dialog" aria-label="Add a Spark">
        {/* Sticky, so the query stays reachable while you scroll 437 rows past
            it. */}
        <div className="spark-search-band">
          <input
            className="uma-search"
            type="search"
            aria-label={`${label} spark search`}
            placeholder="Search Sparks…"
            value={query}
            autoFocus
            onChange={(e) => setQuery(e.target.value)}
          />
        </div>
        {/* The reference is committed and works offline; the favorites are
            server state behind Access. Said separately so a failed list fetch
            never costs you the browse. */}
        {sparkLists.failed && (
          <p className="spark-note">
            Couldn't load your lists — browsing still works.
          </p>
        )}
        {/* The sections share a WRAPPER so "the first heading hugs the band
            above it" can be written as `:first-child` against the wrapper
            alone. Positional selectors against the popout itself get defeated
            by the failure note above, which slides in between exactly when the
            fetch has failed. */}
        <div className="spark-sections">
          {favorites.length > 0 && (
            <div className="spark-section">
              <div className="spark-section-head">Favorites</div>
              <SparkRows options={favorites} {...rowProps} />
            </div>
          )}
          {sections.map((s) => (
            <div key={s.kind} className="spark-section">
              <div className="spark-section-head">{SPARK_TYPE_LABELS[s.kind]}</div>
              <SparkRows options={s.options} {...rowProps} />
            </div>
          ))}
        </div>
        {sections.length === 0 && favorites.length === 0 && (
          <span className="empty">No sparks match.</span>
        )}
      </div>
    </>
  );
}

export function SparkChooser({
  label,
  factors,
  refs,
  sparkLists,
  cardId,
  charaId,
  cardOwner,
  onChange,
  onError,
}: {
  // Distinguishes the choosers on one page for aria/testing.
  label: string;
  factors: readonly SlotFactor[];
  refs: readonly FactorRef[];
  sparkLists: SparkListStore;
  // Who is cast in this node. A green's key IS a card_id, so these decide
  // which greens the node can hold at all — see greenFilter.
  cardId: number | null;
  charaId: number | null;
  cardOwner: (cardId: number) => string | null;
  onChange: (update: (current: readonly SlotFactor[]) => SlotFactor[]) => void;
  onError: (message: string) => void;
}) {
  const [open, setOpen] = useState(false);
  // An UPDATER, not an array: the popout stays open across adds, so two clicks
  // resolved against the same render would each compute `[...factors, x]` from
  // one base and the second would drop the first.
  const add = (option: Option, stars: number) =>
    onChange((current) => [...current, { kind: option.kind, key: option.key, stars }]);
  return (
    <div className="spark-add">
      {/* No ellipsis: a button that opens a dialog doesn't take one, so the
          mark keeps meaning "in flight" or "unresolved". */}
      <button
        className="spark-open"
        aria-haspopup="dialog"
        aria-expanded={open}
        onClick={() => {
          // Only when the last attempt failed: the lists are page-scoped
          // reference-ish state, and re-fetching them on every open would be a
          // request per click for something that rarely changes.
          if (sparkLists.failed) sparkLists.onReload();
          setOpen(true);
        }}
      >
        Add a Spark
      </button>
      {open && (
        <ChooserPopout
          // Remounts per open (re-snapshotting the favorites and clearing an
          // abandoned query) and whenever a fetch of the lists LANDS, so a
          // popout opened mid-fetch re-snapshots instead of showing no
          // Favorites section at all.
          //
          // The generation, not a loaded/loading flag: the retry above fires
          // precisely when loading is already over, so a boolean key would
          // never change and the popout that triggered the retry would keep
          // the empty snapshot it opened with.
          key={sparkLists.epoch}
          label={label}
          factors={factors}
          refs={refs}
          sparkLists={sparkLists}
          cardId={cardId}
          charaId={charaId}
          cardOwner={cardOwner}
          onAdd={add}
          onError={onError}
          onClose={() => setOpen(false)}
        />
      )}
    </div>
  );
}
