import { useEffect, useState } from "react";
import type { FactorRef, SlotFactor, SlotFactorKind, WatchedSpark } from "../api";
import { deriveCharaId } from "../blueprint";
import { SPARK_TYPE_LABELS, SPARK_TYPE_ORDER, sparkId } from "../procs";
// `toggle` is what applies DEFAULT_HUNTING — the default lives in one place
// in the store (#33), and the chooser must not restate it.
import { isWatched, setHunting, toggle, type WatchedStore } from "../sparks";

// Hand entry for a member's non-pink sparks: a popout that BROWSES the 432
// factors, with the ones you've favorited at the top of it.
//
// It replaces the inline search this file used to be (DECISIONS.md #35,
// reversing #30's "an add-one affordance, not a browser"). That search worked
// perfectly if you already knew a name and not at all otherwise — typing "s"
// returned eight of 309 matches and a line reading "301 more". The popout
// still holds a search box, so the typist's path survives one click behind a
// button; what it adds is a way to find a spark you can't spell.
//
// ADDING is all it does, and adding includes the LEVEL — three buttons per
// row, so a 3★ is one click at the moment you are choosing the spark
// (DECISIONS.md #34). Nothing here can change a chance in the table behind it.
//
// FAVOURITING is a different act from adding, deliberately (#35): a filler
// white you type onto every node must not land in #27's watched block, and a
// row must not move under the pointer that just clicked it.
//
// A roster or lineage pick never needs any of this — hers are decoded from
// the dump — so it only appears on hand-built nodes, which is also why it is
// not offered inside a locked branch.

// The browse sections, in the same order the spark tables group by
// (procs.ts), minus the pink the document doesn't hand-enter. Not "whites
// first" despite whites being 256 of the 432: the sections are headed and
// nothing is hidden, so the reader scrolls rather than losing rows off a cap
// — which is the bias #30 caught, and it does not apply to a list with no
// cap in it.
const BROWSE_KINDS: SlotFactorKind[] = (
  ["white", "unique", "race", "scenario"] as SlotFactorKind[]
).sort((a, b) => SPARK_TYPE_ORDER[a] - SPARK_TYPE_ORDER[b]);

// A green spark's factor key IS a card_id — `app/ingest.py` says so in its
// header ("key is the source card_id"), the reference agrees (95 of the 97
// released cards have a unique factor at their own id), and a real roster
// agrees at n=1372: every veteran and lineage member carries at most ONE
// green, and it is always her own card. A uma can LEARN another uma's unique
// during a run; she can never carry the spark for one.
//
// So the green a node can hold is decided by who is cast in it, and offering
// all 137 is offering 136 sparks that member cannot have — with a proc
// estimate waiting behind each. One rule, three tiers (DECISIONS.md #36):
//
//   card known      → her card's unique, which is one row or none
//   chara only      → that character's 1–3 variants
//   neither         → all 137, each named with the uma it belongs to
//
// The middle tier is for a slot carrying `chara_id` without `card_id`: the
// picker always sets both, but the type allows it and a legacy row may not.
// Only `unique` is card-bound — pink, race, white and scenario belong to
// anyone.
const greenFilter =
  (cardId: number | null, charaId: number | null) =>
  (option: Option): boolean => {
    if (option.kind !== "unique") return true;
    if (cardId !== null) return option.key === cardId;
    if (charaId !== null) return deriveCharaId(option.key) === charaId;
    return true;
  };

// A row the chooser can offer: a spark from the reference, or one the
// reference doesn't know. Watched keys are deliberately not validated against
// `app/data` (#33) — the reference is regenerated by hand and can run behind
// a dump — so a favorite may resolve to no name and still be perfectly
// addable, its kind being what decides the base rate.
type Option = { kind: SlotFactorKind; key: number; name: string };

const optionOf = (ref: FactorRef): Option => ref;

const unknownOption = (spark: Pick<WatchedSpark, "kind" | "key">): Option => ({
  kind: spark.kind,
  key: spark.key,
  // The same degradation ProcPanel uses for a stored spark the reference
  // can't name, rather than a blank row.
  name: `Unknown (${spark.key})`,
});

function SparkRows({
  options,
  held,
  watched,
  watchedFailed,
  busy,
  cardOwner,
  onAdd,
  onFavorite,
  onHunting,
}: {
  options: Option[];
  held: Set<string>;
  watched: WatchedSpark[];
  watchedFailed: boolean;
  busy: boolean;
  // Names the uma a green belongs to. Only meaningful where the green list
  // is NOT already narrowed to one card — on a cast node the panel above
  // says whose sparks these are.
  cardOwner: (cardId: number) => string | null;
  onAdd: (option: Option, stars: number) => void;
  onFavorite: (option: Option) => void;
  onHunting: (option: Option, hunting: boolean) => void;
}) {
  return (
    <ul className="spark-matches">
      {options.map((o) => {
        const fav = isWatched(watched, o.kind, o.key);
        const hunting = watched.find(
          (w) => w.kind === o.kind && w.key === o.key
        )?.hunting;
        return (
          <li key={sparkId({ type: o.kind, key: o.key })}>
            {/* Favoriting is its own control, never a side effect of adding:
                every filler white you type onto a grandparent would otherwise
                land in #27's uncapped block, and the row would climb out from
                under the pointer as the favorites re-sorted. Disabled rather
                than hidden when the list didn't load, so the chooser doesn't
                silently change shape on a fetch failure. */}
            <button
              className={fav ? "spark-fav active" : "spark-fav"}
              aria-pressed={fav}
              // The identity on the control, like the add buttons carry it:
              // the reference holds two distinct whites both called
              // "Pressure", so anything driving this list by displayed name
              // can star the wrong (kind, key).
              data-spark={sparkId({ type: o.kind, key: o.key })}
              aria-label={`Favorite ${o.name}`}
              disabled={watchedFailed || busy}
              onClick={() => onFavorite(o)}
            >
              {fav ? "★" : "☆"}
            </button>
            <span className="spark-hit">
              {/* The kind is part of the identity here, which is why it
                  survives in the chooser after #30 cut it from the proc
                  tables: you are picking BETWEEN kinds, and several race and
                  scenario sparks share wording with skills. */}
              <span className={`proc-kind proc-kind-${o.kind}`}>
                {SPARK_TYPE_LABELS[o.kind]}
              </span>
              {o.name}
              {/* Whose green this is. Dimmed and after the name, because the
                  spark is what you are picking and the uma is what tells two
                  of them apart — 137 anonymous greens is a list you cannot
                  navigate. Absent for the 42 uniques whose card has not
                  reached Global. */}
              {o.kind === "unique" && cardOwner(o.key) !== null && (
                <span className="spark-owner">{cardOwner(o.key)}</span>
              )}
            </span>
            {held.has(sparkId({ type: o.kind, key: o.key })) ? (
              // Shown, marked, rather than filtered into silence: finding the
              // right name and getting nothing back reads as "no such spark".
              // The level it was added at lives in the table behind this, with
              // the ✕ that undoes it.
              <span className="spark-held">Added</span>
            ) : (
              // Not a `radiogroup`: these three don't hold a value between
              // them, they are three different add actions. Each names its own
              // outcome, because "3★" alone is meaningless read out of the row
              // it sits in.
              <span className="seg-group" role="group">
                {[1, 2, 3].map((n) => (
                  <button
                    key={n}
                    className="seg"
                    // The spark's identity on the button, so anything driving
                    // this list picks by (kind, key) rather than by the
                    // displayed name — several race and scenario sparks
                    // contain a skill's name as a substring, and the reference
                    // holds two distinct whites both called "Pressure".
                    data-spark={sparkId({ type: o.kind, key: o.key })}
                    data-stars={n}
                    aria-label={`Add ${o.name} at ${n}★`}
                    onClick={() => onAdd(o, n)}
                  >
                    {n}★
                  </button>
                ))}
              </span>
            )}
            {/* The hunting bit, on its own line and only once the row is
                watched. #33 defaults a new favorite to hunting because adding
                is a deliberate pick, and says filler is "one click off at the
                moment you add it" — this is that moment, so the control has to
                be here rather than waiting for #27's surface. Its own line
                because the row already carries a star, a kind tag, a name and
                three buttons, and at 358px (the popout on a 390px phone) a
                fifth control on the line takes the name's width. */}
            {fav && (
              <span className="spark-hunt-line">
                <button
                  className={hunting === true ? "spark-hunt active" : "spark-hunt"}
                  aria-pressed={hunting === true}
                  data-spark={sparkId({ type: o.kind, key: o.key })}
                  aria-label={`Hunting ${o.name}`}
                  title="Breeding for this, not just quick to type"
                  disabled={busy}
                  onClick={() => onHunting(o, hunting !== true)}
                >
                  Hunting
                </button>
              </span>
            )}
          </li>
        );
      })}
    </ul>
  );
}

function ChooserPopout({
  label,
  factors,
  refs,
  watched,
  cardId,
  charaId,
  cardOwner,
  onAdd,
  onError,
  onClose,
}: {
  label: string;
  factors: readonly SlotFactor[];
  refs: readonly FactorRef[];
  watched: WatchedStore;
  cardId: number | null;
  charaId: number | null;
  cardOwner: (cardId: number) => string | null;
  onAdd: (option: Option, stars: number) => void;
  onError: (message: string) => void;
  onClose: () => void;
}) {
  const [query, setQuery] = useState("");
  const [busy, setBusy] = useState(false);
  // WHICH sparks sit in the Favorites section, snapshotted for the life of
  // this open. MEMBERSHIP is frozen; the ★ and the Hunting pill stay live off
  // `watched`. Without the freeze, favoriting a row lifts it out of its kind
  // section and the add buttons you were reaching for are somewhere else —
  // the "row moves under the pointer that just clicked it" failure #34 spent
  // an entry closing, arriving by another route.
  //
  // It has to be membership rather than `watched ∩ snapshot`, which is what
  // shipped first and was wrong in the mirror-image way: UN-starring a row
  // dropped it out of Favorites while the frozen set still hid it from its
  // kind section, so the spark vanished from the popout entirely and could
  // not be added at all until you closed and reopened. Frozen membership
  // means un-starring empties the star and moves nothing.
  //
  // Null until the watched list has SETTLED. Snapshotting an empty list
  // during the mount fetch would leave this open with no Favorites section at
  // all and the user's favorites scattered through the kind sections as
  // filled stars — the exact "same spark, wrong place" state the freeze
  // exists to avoid.
  // Plain lazy state, taken once per mount. The caller REMOUNTS this popout
  // when the watched list settles (see the `key` below), which is what keeps
  // the snapshot from freezing an empty list mid-fetch without needing an
  // effect or a ref read during render.
  const [pinnedRows] = useState(() =>
    watched.list.map((w) => ({ kind: w.kind, key: w.key }))
  );
  const pinned = new Set(pinnedRows.map((w) => sparkId({ type: w.kind, key: w.key })));

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onClose]);

  const held = new Set(factors.map((f) => sparkId({ type: f.kind, key: f.key })));
  const names = new Map(
    refs.map((r) => [sparkId({ type: r.kind, key: r.key }), r.name])
  );
  const q = query.trim().toLowerCase();
  // Applied before anything else, and to the favorites too: a green you
  // favorited is still a green this member cannot carry, so pinning it to
  // the top of a node it does not belong to would be the one place the rule
  // leaks.
  const possible = greenFilter(cardId, charaId);
  // One rule for every section: the query filters, the sections and their
  // order never change, and hits rank by where the query lands in the name
  // then alphabetically — which is a no-op when there is no query, the
  // reference arriving sorted by (kind, name) already. Deliberately NOT the
  // order the reference serves under a query: capping that order directly is
  // what returned eight race sparks and hid every white match behind them
  // (#30). Nothing is capped here, so the ranking only decides what you read
  // first, but it decides it the same way.
  const matching = (options: Option[]): Option[] => {
    const hits = options.filter((o) => possible(o) && o.name.toLowerCase().includes(q));
    if (q === "") return hits;
    return hits.sort(
      (a, b) =>
        a.name.toLowerCase().indexOf(q) - b.name.toLowerCase().indexOf(q) ||
        a.name.localeCompare(b.name)
    );
  };

  // Insertion order, oldest first, which is what the store's own `list` gives
  // and what its row ids mean (#33). Built from the frozen membership, so a
  // row stays put when you un-star it.
  const favorites = matching(
    pinnedRows.map((w) => {
      const name = names.get(sparkId({ type: w.kind, key: w.key }));
      return name === undefined ? unknownOption(w) : { kind: w.kind, key: w.key, name };
    })
  );
  // A favorite is in the Favorites section and NOWHERE ELSE. Rendering it
  // in its kind section too is the same spark twice on one surface, in two
  // idioms — the duplication #45 deleted the held list to remove, and it
  // arrives here as "which of these two rows did I already star". The
  // snapshot is what decides, so nothing disappears from under the pointer
  // when you favorite it: it stays where it is until the next open.
  const sections = BROWSE_KINDS.map((kind) => ({
    kind,
    options: matching(
      refs
        .filter(
          (r) => r.kind === kind && !pinned.has(sparkId({ type: r.kind, key: r.key }))
        )
        .map(optionOf)
    ),
  })).filter((s) => s.options.length > 0);

  // Non-optimistic: `sparks.ts` returns the list the server ended up with, so
  // the star only moves once the row exists.
  //
  // A failure is reported through the PAGE toast rather than a note inside
  // this popout. Dismissing the popout while a PUT is in flight is one
  // keystroke, and a note that unmounts with the surface it lives on reports
  // nothing at all — the star silently reverts and #27's block is quietly
  // missing a spark the user watched themselves mark. The toast is
  // position-fixed and drawn over the backdrops, so it is readable with the
  // popout open too.
  //
  // The message is the CALLER's, because the two controls fail differently
  // and this helper serves both. A failed Hunting toggle reported as "couldn't
  // save that favorite" names a control the user did not touch and an outcome
  // that did not happen — and the sane reaction to it, re-clicking the ★,
  // deletes the favorite they were trying to keep.
  const write = async (op: () => Promise<WatchedSpark[]>, failure: string) => {
    setBusy(true);
    try {
      watched.onChange(await op());
    } catch {
      onError(failure);
    } finally {
      setBusy(false);
    }
  };

  const rowProps = {
    held,
    watched: watched.list,
    watchedFailed: watched.failed,
    busy,
    // The owner is only worth printing where the list is still ambiguous.
    // Narrowed to one card, the panel above already names her, and a third
    // repetition on the single row is the width #30 fought for.
    cardOwner: cardId === null ? cardOwner : () => null,
    onAdd,
    onFavorite: (o: Option) =>
      void write(
        () => toggle(watched.list, o.kind, o.key),
        "Couldn't save that favorite — try again."
      ),
    onHunting: (o: Option, hunting: boolean) =>
      void write(
        () => setHunting(watched.list, o.kind, o.key, hunting),
        "Couldn't save that Hunting change — try again."
      ),
  };

  return (
    <>
      {/* Dismisses on mousedown, not click: Chrome freezes the OS cursor when
          a click unmounts the element under it, which reads as "hover is
          broken" until the next click. The filter panel's popouts do the
          same. */}
      <div className="uma-popout-backdrop" onMouseDown={onClose} />
      <div className="uma-popout spark-popout" role="dialog" aria-label="Add a Spark">
        {/* Sticky, so the query stays reachable while you scroll 432 rows
            past it — that is the difference between a browser and a list you
            have to leave in order to re-query. */}
        <div className="spark-search-band">
          <input
            className="uma-search"
            type="search"
            // Kept as the label the inline search carried, so one box on the
            // page still answers to this node.
            aria-label={`${label} spark search`}
            placeholder="Search Sparks…"
            value={query}
            autoFocus
            onChange={(e) => setQuery(e.target.value)}
          />
        </div>
        {/* The reference is committed and works offline; the favorites are
            server state behind Access. A chooser that can't be browsed
            because a list of favorites didn't load would be the failure
            doing the most damage, so the two are said separately and only the
            favorites go away. */}
        {watched.failed && (
          <p className="spark-note">
            Couldn't load your favorites — browsing still works.
          </p>
        )}
        {/* Every section is the same element, Favorites included, and they
            share a WRAPPER so "the first heading hugs the band above it" can
            be written as `:first-child` against that wrapper alone.
            Positional selectors against the popout kept matching the wrong
            thing: `:first-of-type` matches on TAG, so every section being a
            div made each KIND heading the first of its type and Favorites
            never one; the adjacent-sibling rule that replaced it was in turn
            defeated by the note above, which slides between the band and the
            first section exactly when the fetch has failed. Nothing rendered
            before this wrapper can reach inside it. */}
        <div className="spark-sections">
          {favorites.length > 0 && (
            <div className="spark-section">
              <div className="spark-section-head">Favorites</div>
              <SparkRows options={favorites} {...rowProps} />
            </div>
          )}
          {sections.map((s) => (
            <div key={s.kind} className="spark-section">
              <div className="spark-section-head">{SPARK_TYPE_LABELS[s.kind]}</div>
              <SparkRows options={s.options} {...rowProps} />
            </div>
          ))}
        </div>
        {sections.length === 0 && favorites.length === 0 && (
          <span className="empty">No sparks match.</span>
        )}
      </div>
    </>
  );
}

export function SparkChooser({
  label,
  factors,
  refs,
  watched,
  cardId,
  charaId,
  cardOwner,
  onChange,
  onError,
}: {
  // Distinguishes the choosers on one page for aria/testing, as the pink
  // editor does.
  label: string;
  factors: readonly SlotFactor[];
  refs: readonly FactorRef[];
  // The favorites, their generation, and the two writers — see WatchedStore.
  // `onReload` matters because the load happens once at page mount, so a
  // backend blip lasting one second would otherwise disable every ★ until a
  // hard reload. Opening the chooser is the moment the list is wanted, so it
  // is the moment to try again.
  watched: WatchedStore;
  // Who is cast in this node. A green's key IS a card_id, so these decide
  // which greens the node can hold at all — see greenFilter.
  cardId: number | null;
  charaId: number | null;
  cardOwner: (cardId: number) => string | null;
  onChange: (update: (current: readonly SlotFactor[]) => SlotFactor[]) => void;
  onError: (message: string) => void;
}) {
  const [open, setOpen] = useState(false);
  // Adding does NOT touch the watched list, in either direction — see the
  // header. The blueprint edit is local and the autosave owns it; a watched
  // row is a round-trip, and coupling them means a spark add can fail because
  // a PUT did.
  // An UPDATER, not an array. The popout stays open across adds, so adding
  // three whites in a row is the ordinary flow — and two clicks resolved
  // against the same render both computed `[...factors, x]` from one base,
  // with the second replacing the first wholesale. The spark the user watched
  // themselves click never reached the design, and the autosave persisted the
  // shorter list.
  const add = (option: Option, stars: number) =>
    onChange((current) => [...current, { kind: option.kind, key: option.key, stars }]);
  return (
    <div className="spark-add">
      {/* No ellipsis: a button that opens a dialog doesn't take one, so the
          mark keeps meaning "in flight" or "unresolved". The box inside keeps
          its own. */}
      <button
        className="spark-open"
        aria-haspopup="dialog"
        aria-expanded={open}
        onClick={() => {
          // Only when the last attempt failed: the list is page-scoped
          // reference-ish state, and re-fetching it on every open would be a
          // request per click for something that rarely changes.
          if (watched.failed) watched.onReload();
          setOpen(true);
        }}
      >
        Add a Spark
      </button>
      {open && (
        <ChooserPopout
          // Remounted per open, which is what re-snapshots the favorites'
          // order and clears an abandoned query — the panel keeps its position
          // in the tree when you click another ancestor, so a query left
          // behind would follow you there.
          //
          // Also remounted whenever a FETCH of the watched list lands, so a
          // popout opened during the mount fetch re-snapshots instead of
          // showing no Favorites section at all with the user's stars
          // scattered through the kind sections. It costs a query typed inside
          // that sub-second window.
          //
          // The generation, not a loaded/loading flag: the retry above fires
          // precisely when loading is already over, so a boolean key never
          // changes and the popout that triggered the retry would keep the
          // empty snapshot it opened with — the same failure, reached the
          // other way round.
          key={watched.epoch}
          label={label}
          factors={factors}
          refs={refs}
          watched={watched}
          cardId={cardId}
          charaId={charaId}
          cardOwner={cardOwner}
          onAdd={add}
          onError={onError}
          onClose={() => setOpen(false)}
        />
      )}
    </div>
  );
}
