"""The watched-spark list (DECISIONS.md #33, issue #39).

Database-backed for the same reason test_isolation.py is: what these assert
is the table — insertion order, per-owner uniqueness, and that nothing here
filters against the factor reference. Fixtures come from conftest.py, so the
skip/PYTEST_REQUIRE_DB rules apply identically.
"""
from __future__ import annotations

from typing import Any

import pytest

from app.models import User

WATCHED = "/api/watched-sparks"


async def put(as_user: Any, user: User, kind: str, key: int, **body: Any):
    async with as_user(user) as http:
        return await http.put(
            f"{WATCHED}/{kind}/{key}", json={"hunting": True, "groups": [], **body}
        )


async def listing(as_user: Any, user: User) -> list[dict[str, Any]]:
    async with as_user(user) as http:
        response = await http.get(WATCHED)
    assert response.status_code == 200
    return response.json()


# ---------- the row ----------

async def test_a_watched_spark_round_trips(client: Any, users: list[User]):
    a, _ = users
    response = await put(client, a, "white", 2010, groups=["Front Runner"])
    assert response.status_code == 200
    assert response.json() == {
        "kind": "white",
        "key": 2010,
        "hunting": True,
        "groups": ["Front Runner"],
    }
    assert await listing(client, a) == [response.json()]


async def test_hunting_defaults_true(client: Any, users: list[User]):
    """The default #39 settled: adding is a deliberate pick, so it counts as
    'I want this outcome' until the user says otherwise."""
    a, _ = users
    async with client(a) as http:
        response = await http.put(f"{WATCHED}/race/40", json={})
    assert response.json()["hunting"] is True


async def test_an_unknown_key_is_accepted(client: Any, users: list[User]):
    """No validation against the factor reference, matching blueprint
    factors: app/data is regenerated by hand and can run behind a dump, and
    a spark missing from it is still a legitimate thing to want."""
    a, _ = users
    assert (await put(client, a, "white", 999_999)).status_code == 200
    assert [s["key"] for s in await listing(client, a)] == [999_999]


async def test_an_unknown_kind_is_refused(client: Any, users: list[User]):
    """`kind` decides the proc base rate, so unlike `key` it is closed."""
    a, _ = users
    assert (await put(client, a, "blue", 1)).status_code == 422


# ---------- one row per (kind, key) ----------

async def test_re_putting_replaces_rather_than_duplicating(client: Any, users: list[User]):
    a, _ = users
    await put(client, a, "white", 2010, hunting=True, groups=["Front Runner"])
    await put(client, a, "white", 2010, hunting=False, groups=["Medium"])
    assert await listing(client, a) == [
        {"kind": "white", "key": 2010, "hunting": False, "groups": ["Medium"]}
    ]


async def test_the_same_key_under_a_different_kind_is_a_different_spark(
    client: Any, users: list[User]
):
    """Uniqueness is (kind, key), not key — the kinds' id ranges are an
    ingest heuristic rather than a guarantee."""
    a, _ = users
    await put(client, a, "white", 1)
    await put(client, a, "race", 1)
    assert [(s["kind"], s["key"]) for s in await listing(client, a)] == [
        ("white", 1),
        ("race", 1),
    ]


async def test_a_re_put_keeps_its_place_in_the_list(client: Any, users: list[User]):
    """Order is what the chooser shows, so re-hunting an old spark must not
    move it to the end."""
    a, _ = users
    for key in (1, 2, 3):
        await put(client, a, "white", key)
    await put(client, a, "white", 1, hunting=False)
    assert [s["key"] for s in await listing(client, a)] == [1, 2, 3]


async def test_insertion_order_is_preserved(client: Any, users: list[User]):
    a, _ = users
    for key in (30, 10, 20):
        await put(client, a, "white", key)
    assert [s["key"] for s in await listing(client, a)] == [30, 10, 20]


# ---------- groups ----------

async def test_a_spark_may_belong_to_two_builds(client: Any, users: list[User]):
    """The reason this is one list with labels rather than several lists:
    separate lists could only express this by duplicating the row."""
    a, _ = users
    response = await put(client, a, "white", 2010, groups=["Front Runner", "Medium"])
    assert response.json()["groups"] == ["Front Runner", "Medium"]


async def test_group_names_are_trimmed_and_deduped(client: Any, users: list[User]):
    a, _ = users
    response = await put(
        client, a, "white", 2010, groups=["  Front Runner ", "Front Runner"]
    )
    assert response.json()["groups"] == ["Front Runner"]


@pytest.mark.parametrize("groups", [[""], ["   "], ["x" * 41]])
async def test_unusable_group_names_are_refused(
    client: Any, users: list[User], groups: list[str]
):
    a, _ = users
    assert (await put(client, a, "white", 1, groups=groups)).status_code == 422


# ---------- delete ----------

async def test_unwatching_removes_the_row(client: Any, users: list[User]):
    a, _ = users
    await put(client, a, "white", 2010)
    async with client(a) as http:
        assert (await http.delete(f"{WATCHED}/white/2010")).status_code == 204
    assert await listing(client, a) == []


async def test_unwatching_something_unwatched_is_not_an_error(
    client: Any, users: list[User]
):
    """Already gone is the outcome the caller wanted."""
    a, _ = users
    async with client(a) as http:
        assert (await http.delete(f"{WATCHED}/white/12345")).status_code == 204


# ---------- ownership ----------

async def test_lists_are_per_user(client: Any, users: list[User]):
    a, b = users
    await put(client, a, "white", 2010)
    assert await listing(client, b) == []


async def test_two_users_may_watch_the_same_spark_differently(
    client: Any, users: list[User]
):
    a, b = users
    await put(client, a, "white", 2010, hunting=True, groups=["Front Runner"])
    await put(client, b, "white", 2010, hunting=False)
    assert (await listing(client, a))[0]["groups"] == ["Front Runner"]
    assert (await listing(client, b))[0] == {
        "kind": "white",
        "key": 2010,
        "hunting": False,
        "groups": [],
    }


async def test_you_cannot_unwatch_another_users_spark(client: Any, users: list[User]):
    a, b = users
    await put(client, a, "white", 2010)
    async with client(b) as http:
        assert (await http.delete(f"{WATCHED}/white/2010")).status_code == 204
    assert len(await listing(client, a)) == 1
