"""veteran win saddles and blueprints

Veterans gain `win_saddles` (raw won-saddle ids for the affinity win bonus);
existing rows get the empty default and stay valid — real win data arrives on
the next full-replace import. New `blueprints` table persists saved
inheritance designs (DECISIONS.md #16).

Revision ID: 4b934be8d97e
Revises: e1bd001e7128
Create Date: 2026-07-30 05:51:19.037320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b934be8d97e'
down_revision = 'e1bd001e7128'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blueprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('trainee_chara_id', sa.Integer(), nullable=True),
    sa.Column('slots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('veterans', sa.Column('win_saddles', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('veterans', 'win_saddles')
    op.drop_table('blueprints')
    # ### end Alembic commands ###
