"""initial schema

Revision ID: d0d767d80c87
Revises: 
Create Date: 2026-07-29 04:09:17.299303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0d767d80c87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('veteran_count', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veterans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('trained_chara_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('chara_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('outfit', sa.String(length=100), nullable=False),
    sa.Column('rarity', sa.Integer(), nullable=False),
    sa.Column('talent_level', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('rank_score', sa.Integer(), nullable=False),
    sa.Column('fans', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('stamina', sa.Integer(), nullable=False),
    sa.Column('power', sa.Integer(), nullable=False),
    sa.Column('guts', sa.Integer(), nullable=False),
    sa.Column('wiz', sa.Integer(), nullable=False),
    sa.Column('proper_distance_short', sa.Integer(), nullable=False),
    sa.Column('proper_distance_mile', sa.Integer(), nullable=False),
    sa.Column('proper_distance_middle', sa.Integer(), nullable=False),
    sa.Column('proper_distance_long', sa.Integer(), nullable=False),
    sa.Column('proper_ground_turf', sa.Integer(), nullable=False),
    sa.Column('proper_ground_dirt', sa.Integer(), nullable=False),
    sa.Column('proper_running_style_nige', sa.Integer(), nullable=False),
    sa.Column('proper_running_style_senko', sa.Integer(), nullable=False),
    sa.Column('proper_running_style_sashi', sa.Integer(), nullable=False),
    sa.Column('proper_running_style_oikomi', sa.Integer(), nullable=False),
    sa.Column('register_time', sa.String(length=19), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lineage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trained_chara_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('veterans')
    op.drop_table('imports')
    # ### end Alembic commands ###
