"""add veteran_tags

Revision ID: f99279d25b3c
Revises: d0d767d80c87
Create Date: 2026-07-29 04:52:10.724237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f99279d25b3c'
down_revision = 'd0d767d80c87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veteran_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trained_chara_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trained_chara_id', 'tag', name='uq_veteran_tag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('veteran_tags')
    # ### end Alembic commands ###
