import { api, type SlotFactorKind, type SparkList, type SparkRef } from "./api";
import { writeStore } from "./storage";

// The user's named spark lists — "Front Runner", "Medium" — and the reads
// every feature does over them (DECISIONS.md #37).
//
// The lists are server-backed; which ones are ACTIVE is not. A list belongs to
// a user and spans devices, so it is a row. Which of them you are working
// against right now is a view, so it is `localStorage` — the phone being on a
// different build from the desktop is a feature. Hence async mutators and
// pure reads over lists the caller holds: a module-held cache with a
// synchronous `isFavorite()` would be a second copy of server state with no
// way to know it had gone stale.
//
// ITS OWN MODULE, NOT filters.ts — which holds roster-page state, and would
// invite a `reconcile` pass by proximity. These lists must never get one:
// membership is deliberately not validated against `app/data`, because the
// reference is regenerated by hand and can run behind a dump, so a spark it
// cannot name is still a legitimate thing to want. Reconciling would silently
// delete every favorite for a skill newer than the last regen.

export type { SparkList, SparkRef } from "./api";

export const ACTIVE_LISTS_STORE = "umalab.sparkLists.active";

// Everything a consumer needs to render and write the lists, as ONE prop —
// the chooser sits three levels below the page that owns the fetch.
export type SparkListStore = {
  lists: SparkList[];
  // Which generation of `lists` this is. Zero until the first fetch SETTLES,
  // then bumped by every fetch that lands, including a retry — which an
  // "already loaded" boolean cannot express, since a retry only happens once
  // loading is over. The chooser keys its popout on this. Writes deliberately
  // do NOT bump it: the frozen membership is what keeps a row from moving out
  // from under the pointer that starred it.
  epoch: number;
  // Whether the LAST attempt rejected, which an empty array cannot say — a
  // user with no lists yet and a user whose fetch failed hold the same value,
  // and only one of them has a reason to see the controls disabled.
  failed: boolean;
  // Empty means "everything", not "nothing" — see `activeSparks`.
  active: number[];
  // Non-optimistic: the mutators return what the server ended up with, so a
  // checkbox only moves once the row says so.
  onChange: (next: SparkList[]) => void;
  onActiveChange: (next: number[]) => void;
  // Re-fetch, for the chooser opening after a FAILED fetch. Not a general
  // staleness fix: it bumps `epoch`, so calling it while the popout is open
  // rebuilds it and discards the user's search and any picker they had open.
  onReload: () => void;
};

const sameSpark = (spark: SparkRef, kind: SlotFactorKind, key: number) =>
  spark.kind === kind && spark.key === key;

const refId = (spark: SparkRef) => `${spark.kind}:${spark.key}`;

// ---------- reads ----------
// Pure over the lists the caller already has in state, so a row can be
// rendered without a fetch per cell.

export const listById = (
  lists: SparkList[],
  id: number
): SparkList | undefined => lists.find((list) => list.id === id);

/** Every list holding this spark — what the picker checks its boxes from. */
export const listsWith = (
  lists: SparkList[],
  kind: SlotFactorKind,
  key: number
): SparkList[] =>
  lists.filter((list) => list.sparks.some((s) => sameSpark(s, kind, key)));

/** In at least one list — what the ★ renders. Favorites IS the union. */
export const isFavorite = (
  lists: SparkList[],
  kind: SlotFactorKind,
  key: number
): boolean =>
  lists.some((list) => list.sparks.some((s) => sameSpark(s, kind, key)));

/**
 * The union of the given lists, deduped, first occurrence winning. List order
 * then membership order — the server's sort, then the user's arrangement.
 */
export const union = (lists: SparkList[]): SparkRef[] => {
  const seen = new Map<string, SparkRef>();
  for (const list of lists) {
    for (const spark of list.sparks) {
      if (!seen.has(refId(spark))) seen.set(refId(spark), spark);
    }
  }
  return [...seen.values()];
};

/** Everything the user has anywhere — the chooser's Favorites section. */
export const favorites = (lists: SparkList[]): SparkRef[] => union(lists);

/**
 * The sparks in play: the union of the ACTIVE lists.
 *
 * **Nothing selected means everything.** Every user starts with no lists and
 * no selection, and a block that renders empty on first use reads as broken
 * rather than as unconfigured (DECISIONS.md #37). Ids naming no list are
 * dropped silently — a list deleted on another device leaves a stale id here.
 */
export const activeSparks = (
  lists: SparkList[],
  active: number[]
): SparkRef[] => {
  const chosen = lists.filter((list) => active.includes(list.id));
  return union(chosen.length === 0 ? lists : chosen);
};

/** Every list name in use, in the user's order — what the active-list
 *  selector (#67) renders. No in-app caller yet; not dead code. */
export const listNames = (lists: SparkList[]): string[] =>
  lists.map((list) => list.name);

// ---------- the active selection (device-local) ----------

/**
 * Shape-checked in full, falling back to "none selected" — which means
 * "everything", so a corrupt key degrades to showing more than you asked for
 * rather than to an empty block.
 */
export function loadActiveLists(store: string = ACTIVE_LISTS_STORE): number[] {
  try {
    const raw = localStorage.getItem(store);
    if (raw) {
      const parsed: unknown = JSON.parse(raw);
      if (
        Array.isArray(parsed) &&
        parsed.every((id) => typeof id === "number" && Number.isInteger(id))
      ) {
        return parsed;
      }
    }
  } catch {
    // absent, blocked, or not JSON — fall through to the default
  }
  return [];
}

export const saveActiveLists = (
  active: number[],
  store: string = ACTIVE_LISTS_STORE
): void => writeStore(store, active);

/** Pure — the caller persists what it gets. */
export const toggleActive = (active: number[], id: number): number[] =>
  active.includes(id) ? active.filter((n) => n !== id) : [...active, id];

// ---------- writes ----------
// Each returns the new array of lists for the caller to put back in state.
// The server is the authority on order and membership, so a returned list
// replaces the local one rather than being merged into it.
//
// A write folds in the ONE list it touched rather than adopting a fresh
// fetch: the chooser freezes its Favorites membership at open and filters the
// kind sections against that snapshot, so a spark the snapshot has never seen
// would arrive as a filled ★ in a kind section. Wholesale refresh is
// `onReload`'s job, and it bumps `epoch` so the snapshot is retaken.

/** Server order: position, ties on id — where the next GET would put it. */
const ordered = (lists: SparkList[]): SparkList[] =>
  [...lists].sort((a, b) => a.position - b.position || a.id - b.id);

const replacing = (lists: SparkList[], saved: SparkList): SparkList[] =>
  ordered(
    lists.some((list) => list.id === saved.id)
      ? lists.map((list) => (list.id === saved.id ? saved : list))
      : [...lists, saved]
  );

export const loadSparkLists = (): Promise<SparkList[]> => api.sparkLists();

/**
 * Create an empty list — creating and filling are separate requests, and a
 * list with nothing in it is a normal state.
 *
 * Rejects with a 409 `ApiError` if the name is taken. Surfaced rather than
 * swallowed: the picker has a field the user can correct.
 */
export async function createList(
  lists: SparkList[],
  name: string
): Promise<SparkList[]> {
  return replacing(lists, await api.createSparkList(name));
}

/**
 * A write whose first half committed and whose second half did not, carrying
 * the state the caller must adopt anyway.
 *
 * Thrown rather than returned so a caller cannot mistake it for success, and
 * carrying `lists` because throwing alone would strand a row that really
 * exists: the caller has to both show the error AND fold in what landed.
 */
export class PartialWrite extends Error {
  constructor(
    readonly lists: SparkList[],
    readonly reason: unknown
  ) {
    super("the list was created but its membership was not saved");
    this.name = "PartialWrite";
  }
}

/**
 * Create a list and put this spark in it — the picker's `New List`, always
 * reached while starring something.
 *
 * **If the create succeeds and the fill fails, the created list is still
 * handed back**, as `PartialWrite.lists`. Rejecting outright would discard a
 * row the server committed: it would appear nowhere, so there would be no
 * pill to retry on, and re-typing the same name would 409 forever against a
 * list the user cannot see. Surfacing it empty means the next click on its
 * pill finishes the job.
 *
 * `PartialWrite.lists` is built from the `lists` this was CALLED with, so
 * adopting it overwrites any write that resolved in between — the price of
 * pure functions over a caller-held list, shared by every mutator here. It
 * cannot fire from the chooser, where `busy` disables the popout for the
 * whole of a write. Stated rather than guarded: a guard would have to be a
 * merge, and a merge needs an identity for "the newest version of a list"
 * that the server does not give us.
 */
export async function createListWith(
  lists: SparkList[],
  name: string,
  kind: SlotFactorKind,
  key: number
): Promise<SparkList[]> {
  const created = await api.createSparkList(name);
  const withList = replacing(lists, created);
  try {
    return await setMembership(withList, created.id, [{ kind, key }]);
  } catch (reason) {
    throw new PartialWrite(withList, reason);
  }
}

export async function renameList(
  lists: SparkList[],
  id: number,
  name: string
): Promise<SparkList[]> {
  return replacing(lists, await api.updateSparkList(id, { name }));
}

/**
 * Delete the list and everything in it. A spark in no other list leaves
 * Favorites with it — the union orphans nothing, so there is nothing to sweep.
 */
export async function deleteList(
  lists: SparkList[],
  id: number
): Promise<SparkList[]> {
  await api.deleteSparkList(id);
  return lists.filter((list) => list.id !== id);
}

/**
 * Replace one list's membership wholesale, matching the route. The cost is
 * that two devices editing one list at once is last-write-wins — accepted,
 * and DECISIONS.md #37 says what closing it would take.
 */
export async function setMembership(
  lists: SparkList[],
  id: number,
  sparks: SparkRef[]
): Promise<SparkList[]> {
  return replacing(lists, await api.updateSparkList(id, { sparks }));
}

/**
 * One checkbox in the picker. Computed from the caller's copy, so a list
 * changed on another device is written from a stale set — the last-write-wins
 * case above, at its narrowest.
 *
 * A list the caller does not have is a no-op rather than a create: the id
 * came from a control rendered off these same lists, so its absence means the
 * list was deleted, and re-creating it would resurrect what another device
 * just removed.
 */
export async function toggleMembership(
  lists: SparkList[],
  id: number,
  kind: SlotFactorKind,
  key: number
): Promise<SparkList[]> {
  const list = listById(lists, id);
  if (list === undefined) return lists;
  const held = list.sparks.some((s) => sameSpark(s, kind, key));
  const sparks = held
    ? list.sparks.filter((s) => !sameSpark(s, kind, key))
    : [...list.sparks, { kind, key }];
  return setMembership(lists, id, sparks);
}
