import {
  ApiError,
  api,
  type ListSparkKind,
  type SlotFactorKind,
  type SparkList,
  type SparkRef,
} from "./api";
import { sparkId } from "./procs";
import { writeStore } from "./storage";

// The user's named spark lists — "Front Runner", "Medium" — and the reads
// every feature does over them (DECISIONS.md #37).
//
// The lists are server-backed; which ones are ACTIVE is not. A list belongs to
// a user and spans devices, so it is a row. Which of them you are working
// against right now is a view, so it is `localStorage` — the phone being on a
// different build from the desktop is a feature. Hence async mutators and
// pure reads over lists the caller holds: a module-held cache with a
// synchronous `isFavorite()` would be a second copy of server state with no
// way to know it had gone stale.
//
// ITS OWN MODULE, NOT filters.ts — which holds roster-page state, and would
// invite a `reconcile` pass by proximity. These lists must never get one:
// membership is deliberately not validated against `app/data`, because the
// reference is regenerated by hand and can run behind a dump, so a spark it
// cannot name is still a legitimate thing to want. Reconciling would silently
// delete every favorite for a skill newer than the last regen.

export type { SparkList, SparkRef } from "./api";

/** What `onChange` accepts — `setState`'s two shapes, for the same reason
 *  React has both: the optimistic paths must update against current state. */
export type SparkListUpdate =
  | SparkList[]
  | ((prev: SparkList[]) => SparkList[]);

export const ACTIVE_LISTS_STORE = "umalab.sparkLists.active";

// Everything a consumer needs to render and write the lists, as ONE prop —
// the chooser sits three levels below the page that owns the fetch.
export type SparkListStore = {
  lists: SparkList[];
  // Which generation of `lists` this is. Zero until the first fetch SETTLES,
  // then bumped by every fetch that lands, including a retry — which an
  // "already loaded" boolean cannot express, since a retry only happens once
  // loading is over. The chooser keys its popout on this. Writes deliberately
  // do NOT bump it: the frozen membership is what keeps a row from moving out
  // from under the pointer that starred it.
  epoch: number;
  // Whether the LAST attempt rejected, which an empty array cannot say — a
  // user with no lists yet and a user whose fetch failed hold the same value,
  // and only one of them has a reason to see the controls disabled.
  failed: boolean;
  // Empty means "everything", not "nothing" — see `activeSparks`.
  active: number[];
  // Takes React's functional form because every write applies against
  // whatever state holds when it lands (issue #69, DECISIONS.md #49): flips
  // and reverts by nature, and the awaited writes because an array built
  // before their round trip would overwrite a flip that landed during it.
  onChange: (next: SparkListUpdate) => void;
  // A toggle, not a value setter: two presses resolved against one render
  // would each compute the next selection from the same stale array and the
  // later write would drop the earlier press — the onSetFactors rule.
  onToggleActive: (id: number) => void;
  // Re-fetch, for the chooser opening after a FAILED fetch. Not a general
  // staleness fix: it bumps `epoch`, so calling it while the popout is open
  // rebuilds it and discards the user's search and any picker they had open.
  onReload: () => void;
};

const sameSpark = (spark: SparkRef, kind: SlotFactorKind, key: number) =>
  spark.kind === kind && spark.key === key;

// Delegates rather than restating the format: `activeSparkIds` feeds these
// straight into row lookups keyed by `sparkId`, so a second copy of the
// literal would be a byte-for-byte contract only a test could police.
const refId = (spark: SparkRef) => sparkId({ type: spark.kind, key: spark.key });

// ---------- reads ----------
// Pure over the lists the caller already has in state, so a row can be
// rendered without a fetch per cell.

export const listById = (
  lists: SparkList[],
  id: number
): SparkList | undefined => lists.find((list) => list.id === id);

/** Every list holding this spark — what the picker checks its boxes from. */
export const listsWith = (
  lists: SparkList[],
  kind: SlotFactorKind,
  key: number
): SparkList[] =>
  lists.filter((list) => list.sparks.some((s) => sameSpark(s, kind, key)));

/** In at least one list — what the ★ renders. Favorites IS the union. */
export const isFavorite = (
  lists: SparkList[],
  kind: SlotFactorKind,
  key: number
): boolean =>
  lists.some((list) => list.sparks.some((s) => sameSpark(s, kind, key)));

/**
 * The union of the given lists, deduped, first occurrence winning. List order
 * then membership order — the server's sort, then the user's arrangement.
 */
export const union = (lists: SparkList[]): SparkRef[] => {
  const seen = new Map<string, SparkRef>();
  for (const list of lists) {
    for (const spark of list.sparks) {
      if (!seen.has(refId(spark))) seen.set(refId(spark), spark);
    }
  }
  return [...seen.values()];
};

/** Everything the user has anywhere — the chooser's Favorites section. */
export const favorites = (lists: SparkList[]): SparkRef[] => union(lists);

/**
 * The lists the selection actually names — selected ∩ existing, in list
 * order. Unlike `activeSparks` there is deliberately NO fallback-to-all:
 * empty here means "no filter", and each caller decides what that renders —
 * for the filter surfaces, the whole unfiltered view (DECISIONS.md #43).
 */
export const chosenLists = (lists: SparkList[], active: number[]): SparkList[] =>
  lists.filter((list) => active.includes(list.id));

/**
 * The sparks in play: the union of the ACTIVE lists.
 *
 * **Nothing selected means everything.** Every user starts with no lists and
 * no selection, and a block that renders empty on first use reads as broken
 * rather than as unconfigured (DECISIONS.md #37). Ids naming no list are
 * dropped silently — a list deleted on another device leaves a stale id here.
 */
export const activeSparks = (
  lists: SparkList[],
  active: number[]
): SparkRef[] => {
  const chosen = chosenLists(lists, active);
  return union(chosen.length === 0 ? lists : chosen);
};

/** `activeSparks` as a membership test, ids in the `kind:key` format the
 *  proc tables key their rows by — what the watched tint checks. */
export const activeSparkIds = (
  lists: SparkList[],
  active: number[]
): Set<string> => new Set(activeSparks(lists, active).map(refId));

// ---------- the active selection (device-local) ----------

/**
 * Shape-checked in full, falling back to "none selected" — which means
 * "everything", so a corrupt key degrades to showing more than you asked for
 * rather than to an empty block.
 */
export function loadActiveLists(store: string = ACTIVE_LISTS_STORE): number[] {
  try {
    const raw = localStorage.getItem(store);
    if (raw) {
      const parsed: unknown = JSON.parse(raw);
      if (
        Array.isArray(parsed) &&
        parsed.every((id) => typeof id === "number" && Number.isInteger(id))
      ) {
        return parsed;
      }
    }
  } catch {
    // absent, blocked, or not JSON — fall through to the default
  }
  return [];
}

export const saveActiveLists = (
  active: number[],
  store: string = ACTIVE_LISTS_STORE
): void => writeStore(store, active);

/** Pure — the caller persists what it gets. */
export const toggleActive = (active: number[], id: number): number[] =>
  active.includes(id) ? active.filter((n) => n !== id) : [...active, id];

// ---------- writes ----------
// The awaited writes (create, rename, delete) each resolve to a FOLD over
// the caller's current state, never to an array: an array would be built
// from the lists as of the call, and adopting it when the write resolves
// would overwrite any optimistic flip that landed during the round trip.
// Membership toggles are optimistic and split
// into a local flip and a background request (issue #69, DECISIONS.md #49).
//
// A write folds in the ONE list it touched rather than adopting a fresh
// fetch: the chooser freezes its Favorites membership at open and filters the
// kind sections against that snapshot, so a spark the snapshot has never seen
// would arrive as a filled ★ in a kind section. Wholesale refresh is
// `onReload`'s job, and it bumps `epoch` so the snapshot is retaken.

/** Server order: creation (`id`) — where the next GET would put it. */
const ordered = (lists: SparkList[]): SparkList[] =>
  [...lists].sort((a, b) => a.id - b.id);

const replacing = (lists: SparkList[], saved: SparkList): SparkList[] =>
  ordered(
    lists.some((list) => list.id === saved.id)
      ? lists.map((list) => (list.id === saved.id ? saved : list))
      : [...lists, saved]
  );

export const loadSparkLists = (): Promise<SparkList[]> => api.sparkLists();

/**
 * Create an empty list — the Lists page's bare create. A list with nothing
 * in it is a normal state.
 *
 * Rejects with a 409 `ApiError` if the name is taken. Surfaced rather than
 * swallowed: the create bar has a field the user can correct.
 */
export async function createList(
  name: string
): Promise<(prev: SparkList[]) => SparkList[]> {
  const saved = await api.createSparkList(name);
  return (prev) => replacing(prev, saved);
}

/**
 * Create a list holding this spark — the picker's `New List`, always reached
 * while starring something. The membership rides the create in one request
 * (issue #69, DECISIONS.md #49), so a refused name leaves nothing behind:
 * there is no half-made list to adopt, which is what retired the
 * `PartialWrite` error the two-request shape needed.
 */
export async function createListWith(
  name: string,
  kind: ListSparkKind,
  key: number
): Promise<(prev: SparkList[]) => SparkList[]> {
  const saved = await api.createSparkList(name, [{ kind, key }]);
  // A fresh id: nothing local can hold a flip for it, so the whole row folds.
  return (prev) => replacing(prev, saved);
}

/**
 * The fold takes the server's name and stamp and nothing else — membership
 * stays the flip's (DECISIONS.md #49), so a rename resolving mid-toggle
 * cannot re-fight the toggle's optimistic state.
 */
export async function renameList(
  id: number,
  name: string
): Promise<(prev: SparkList[]) => SparkList[]> {
  const saved = await api.updateSparkList(id, { name });
  return (prev) =>
    withStamp(
      prev.map((list) =>
        list.id === saved.id ? { ...list, name: saved.name } : list
      ),
      saved.id,
      saved.updated_at
    );
}

/**
 * Delete the list and everything in it. A spark in no other list leaves
 * Favorites with it — the union orphans nothing, so there is nothing to sweep.
 */
export async function deleteList(
  id: number
): Promise<(prev: SparkList[]) => SparkList[]> {
  await api.deleteSparkList(id);
  return (prev) => prev.filter((list) => list.id !== id);
}

/**
 * The list this write named no longer exists — deleted on another device or
 * in another tab. A marker, not a payload: the caller drops the dead row
 * from its CURRENT state with a functional update, so the pill disappears
 * in place with no reload, no `epoch` bump and no remount (issue #66's
 * absorbed #73; the two reverted corrective-reload shapes are recorded
 * there).
 */
export class ListGone extends Error {
  constructor() {
    super("that list was deleted elsewhere");
    this.name = "ListGone";
  }
}

/**
 * One membership, applied locally — the optimistic flip and its revert are
 * this same function with `present` inverted, so a revert states the world
 * it wants instead of undoing a snapshot. A list the caller does not have
 * is a no-op rather than a create: the id came from a control rendered off
 * these same lists, so its absence means the list was deleted, and
 * re-creating it would resurrect what another device just removed. Adds
 * append, matching where the server's member-id order puts a fresh row.
 */
export const withMembership = (
  lists: SparkList[],
  id: number,
  kind: ListSparkKind,
  key: number,
  present: boolean
): SparkList[] =>
  lists.map((list) => {
    if (list.id !== id) return list;
    const held = list.sparks.some((s) => sameSpark(s, kind, key));
    if (held === present) return list;
    return {
      ...list,
      sparks: present
        ? [...list.sparks, { kind, key }]
        : list.sparks.filter((s) => !sameSpark(s, kind, key)),
    };
  });

/**
 * Fold a settled write's `updated_at`, keeping the later stamp (ISO strings
 * compare, and max is immune to responses landing out of order). The rest
 * of the response is deliberately NOT folded: with concurrent pills in
 * flight each response is the whole list as of THAT write, so adopting one
 * could clobber a newer flip or resurrect an older one. The flip is the
 * record; the stamp keeps the Lists page's Last Edited sort honest.
 */
export const withStamp = (
  lists: SparkList[],
  id: number,
  updated_at: string
): SparkList[] =>
  lists.map((list) =>
    list.id === id && updated_at > list.updated_at
      ? { ...list, updated_at }
      : list
  );

// In-flight membership requests by (list, spark) — bookkeeping, not a copy
// of server state, so the no-cache rule in the header holds.
const inflight = new Map<string, Promise<unknown>>();

const pillKey = (id: number, kind: ListSparkKind, key: number) =>
  `${id}|${kind}|${key}`;

// The last membership the server acknowledged per pill — the revert target.
// A failed write's own inverse assumes the write before it landed, which a
// chain of failures breaks: superseded failures revert nothing, so the
// final failure must revert past them all. Re-initialized from the screen
// at every chain start (the screen matches the server when nothing is in
// flight), advanced on each success; entries are only ever read mid-chain,
// so stale ones are harmless and growth is bounded by pills touched.
const acked = new Map<string, boolean>();

/**
 * The request behind an optimistic flip: PUT or DELETE on the member path
 * per `desired` (issue #66's absolute, idempotent verbs). Requests for the
 * SAME (list, spark) chain behind each other — the verbs state end states,
 * so the last click's request lands last and the server converges to the
 * screen — while different pills stay parallel.
 *
 * **A superseded failure resolves `null`.** When a newer write for the same
 * pill is already queued, this write's failure decides nothing: the newer
 * verb states the end state and reports its own outcome. Rejecting anyway
 * made a double-click toast "Couldn't save" while the server ended exactly
 * where the screen shows — and the revert it triggered was already a no-op,
 * `withMembership` being absolute.
 *
 * A 404 with no newer write queued throws `ListGone`; any other final
 * failure passes through for the caller's revert and toast.
 */
export async function syncMembership(
  id: number,
  kind: ListSparkKind,
  key: number,
  desired: boolean
): Promise<SparkList | null> {
  const pill = pillKey(id, kind, key);
  const issue = () =>
    desired ? api.addListSpark(id, kind, key) : api.removeListSpark(id, kind, key);
  // Chained on settlement, not success: a failed predecessor must not wedge
  // the pill, and this request's outcome is its own.
  const run = (inflight.get(pill) ?? Promise.resolve()).then(issue, issue);
  const settled = run.then(
    () => undefined,
    () => undefined
  );
  inflight.set(pill, settled);
  void settled.then(() => {
    if (inflight.get(pill) === settled) inflight.delete(pill);
  });
  try {
    return await run;
  } catch (error) {
    // Still the chain's tail here: the map entry only ever moves when a
    // newer write replaces it, and the delayed cleanup above cannot run
    // before this catch — `settled`'s handler resolves first and only
    // QUEUES the delete behind this continuation.
    if (inflight.get(pill) !== settled) return null;
    if (error instanceof ApiError && error.status === 404) {
      throw new ListGone();
    }
    throw error;
  }
}

/**
 * The whole optimistic toggle, shared by both list surfaces (the chooser's
 * picker and the Lists page's popout — the second surface DECISIONS.md #49
 * named as the extraction trigger): flip now against current state, run the
 * request behind it, fold only the settled `updated_at`. A final failure
 * re-states the last server-acknowledged membership; a superseded write's
 * `null` folds nothing and reports nothing; a `ListGone` drops the dead row
 * in place, no reload and no `epoch` bump. A list the caller's `lists` no
 * longer holds is a no-op — the `withMembership` rule.
 */
export function toggleListSpark(
  lists: SparkList[],
  id: number,
  kind: ListSparkKind,
  key: number,
  onChange: (next: SparkListUpdate) => void,
  onError: (message: string) => void
): void {
  const list = listById(lists, id);
  if (list === undefined) return;
  const desired = !list.sparks.some((s) => sameSpark(s, kind, key));
  const pill = pillKey(id, kind, key);
  // Chain start (syncMembership registers the pill synchronously below).
  if (!inflight.has(pill)) acked.set(pill, !desired);
  onChange((prev) => withMembership(prev, id, kind, key, desired));
  void syncMembership(id, kind, key, desired).then(
    (saved) => {
      if (saved !== null) {
        acked.set(pill, desired);
        onChange((prev) => withStamp(prev, id, saved.updated_at));
      }
    },
    (error: unknown) => {
      if (error instanceof ListGone) {
        onChange((prev) => prev.filter((l) => l.id !== id));
        onError("That list was deleted somewhere else.");
      } else {
        const revert = acked.get(pill) ?? !desired;
        onChange((prev) => withMembership(prev, id, kind, key, revert));
        onError("Couldn't save that list change — try again.");
      }
    }
  );
}

// ---------- the management page's sort (device-local) ----------
// A view over server rows, like the active selection above it — which is why
// it lives here and in localStorage rather than as a column: two devices
// sorting differently is a feature, and there is no curated order to protect
// (`position` was stripped before any UI set one, DECISIONS.md #44).

export const LIST_SORT_STORE = "umalab.sparkLists.sort";

export const LIST_SORTS = ["name", "newest", "edited"] as const;
export type ListSort = (typeof LIST_SORTS)[number];

export function loadListSort(store: string = LIST_SORT_STORE): ListSort {
  try {
    const raw = localStorage.getItem(store);
    if (raw !== null) {
      const parsed: unknown = JSON.parse(raw);
      if ((LIST_SORTS as readonly string[]).includes(parsed as string)) {
        return parsed as ListSort;
      }
    }
  } catch {
    // absent, blocked, or not JSON — fall through to the default
  }
  return "name";
}

export const saveListSort = (sort: ListSort, store: string = LIST_SORT_STORE): void =>
  writeStore(store, sort);

/**
 * Pure and total: every mode falls back to `id` so equal keys cannot swap
 * places between renders. `updated_at` is an ISO timestamp and compares as a
 * string; ties fall to newest-first, matching what "just edited" reads as.
 */
export const sortLists = (lists: SparkList[], sort: ListSort): SparkList[] =>
  [...lists].sort((a, b) => {
    if (sort === "name") return a.name.localeCompare(b.name) || a.id - b.id;
    if (sort === "edited") {
      return b.updated_at.localeCompare(a.updated_at) || b.id - a.id;
    }
    return b.id - a.id;
  });
