import { SLOT_FACTOR_KINDS, type SlotFactorKind } from "./api";
import { writeStore } from "./storage";

// The sparks this user cares about — one list, shared by every feature that
// needs to ask that question (DECISIONS.md #32).
//
// Its own module rather than domain.ts or filters.ts: both existing store
// pairs sit beside the thing they configure (`SORT_STORE` beside
// `sortVeterans`, `FILTER_STORE` beside `matchesFilters`), and this
// configures neither the roster grid nor its filters — it's read by the
// designer's chooser and its proc tables. Living in filters.ts would also
// invite a `reconcile` pass by proximity, which is exactly what this store
// must not have.

// Keyed by the game's factor key, never a name: names are localized strings
// resolved at render time, the key is the identity (DECISIONS.md #30).
//
// `hunting` is the distinction between "keep this handy to type" and "I want
// this outcome" — a bit on a row rather than a second list. `groups` is the
// user's own build names ("Front Runner", "Medium"); a spark that belongs to
// two builds is one row in two groups, which separate lists could only
// express by duplicating it. Empty/absent means ungrouped, which is every row
// until something writes a group.
export type WatchedSpark = {
  kind: SlotFactorKind;
  key: number;
  hunting: boolean;
  groups?: string[];
};

export const WATCHED_SPARK_STORE = "umalab.sparks.watched";

// A newly added spark is hunted. Adding is a deliberate pick — spark, then
// star level — which reads as "I want this outcome", and defaulting to false
// would leave the watched block empty on first use with the bit that fills it
// one the user never saw. Filler you only want handy for typing is one click
// off, at the moment you add it.
export const DEFAULT_HUNTING = true;

const isEntry = (e: unknown): e is WatchedSpark => {
  if (typeof e !== "object" || e === null) return false;
  const w = e as Partial<WatchedSpark>;
  return (
    (SLOT_FACTOR_KINDS as readonly string[]).includes(w.kind as string) &&
    typeof w.key === "number" &&
    Number.isFinite(w.key) &&
    typeof w.hunting === "boolean" &&
    (w.groups === undefined ||
      (Array.isArray(w.groups) && w.groups.every((g) => typeof g === "string")))
  );
};

// Same shape validation as loadFilters/loadSortPref: an unparseable value
// falls back to empty rather than throwing.
//
// Unknown keys are KEPT, unlike reconcileFilters' unmatchable filters. A
// watched spark missing from `app/data` is still a legitimate thing to want —
// the reference is regenerated by hand and can run behind a dump, and #30
// already rules that unknown keys are accepted rather than rejected. A bad
// entry within a good array is dropped on its own; only a value that isn't an
// array at all costs the whole list.
export function loadWatched(store: string = WATCHED_SPARK_STORE): WatchedSpark[] {
  try {
    const raw = localStorage.getItem(store);
    if (raw) {
      const p: unknown = JSON.parse(raw);
      if (Array.isArray(p)) return dedupe(p.filter(isEntry));
    }
  } catch {
    // unreadable storage or garbage value — fall through to the empty list
  }
  return [];
}

// Paired with loadWatched so both ends of the key sit together. writeStore
// owns the quota/private-window judgement for every persisted preference.
export function saveWatched(
  watched: WatchedSpark[],
  store: string = WATCHED_SPARK_STORE
): void {
  writeStore(store, watched);
}

// One entry per (kind, key), matching the uniqueness rule the `factors`
// document already uses. First occurrence wins, so insertion order survives.
const dedupe = (entries: WatchedSpark[]): WatchedSpark[] => {
  const seen = new Set<string>();
  return entries.filter((e) => {
    const id = `${e.kind}:${e.key}`;
    if (seen.has(id)) return false;
    seen.add(id);
    return true;
  });
};

// The module holds the loaded list so the three consumers share one truth
// without threading it through the tree. Every mutator writes through and
// returns the new list, which is what a React caller puts in state — the same
// arrangement the shell has with filters, minus the prop drilling. Loaded
// lazily: nothing touches localStorage until something asks.
let cache: WatchedSpark[] | null = null;

const current = (): WatchedSpark[] => (cache ??= loadWatched());

const commit = (next: WatchedSpark[]): WatchedSpark[] => {
  cache = next;
  saveWatched(next);
  return next;
};

// Ordered by insertion, oldest first. With a group name, only that build's
// sparks — a filter over the one list, never a second store.
export function list(group?: string): WatchedSpark[] {
  const all = current();
  return group === undefined ? all : all.filter((e) => e.groups?.includes(group));
}

// Every group name in use, in the order it was first written. What a group
// control renders; there is no separate registry of names, so a group exists
// exactly as long as a spark is in it.
export function groupNames(): string[] {
  const names = new Set<string>();
  for (const e of current()) for (const g of e.groups ?? []) names.add(g);
  return [...names];
}

const find = (kind: SlotFactorKind, key: number) =>
  current().find((e) => e.kind === kind && e.key === key);

export const isWatched = (kind: SlotFactorKind, key: number): boolean =>
  find(kind, key) !== undefined;

// Unwatched reads as not hunted, so a caller can ask this one question
// instead of two.
export const isHunting = (kind: SlotFactorKind, key: number): boolean =>
  find(kind, key)?.hunting === true;

export const groupsOf = (kind: SlotFactorKind, key: number): string[] =>
  find(kind, key)?.groups ?? [];

// Add at the end, or remove. Returns the new list.
export function toggle(kind: SlotFactorKind, key: number): WatchedSpark[] {
  const all = current();
  return commit(
    isWatched(kind, key)
      ? all.filter((e) => !(e.kind === kind && e.key === key))
      : [...all, { kind, key, hunting: DEFAULT_HUNTING }]
  );
}

const update = (
  kind: SlotFactorKind,
  key: number,
  fn: (e: WatchedSpark) => WatchedSpark
): WatchedSpark[] => {
  const all = current();
  if (!isWatched(kind, key)) return all;
  return commit(all.map((e) => (e.kind === kind && e.key === key ? fn(e) : e)));
};

// Both no-op on a spark that isn't watched: setting a bit on a row that
// doesn't exist would otherwise add one by a side door, and which of add or
// ignore is right belongs to the caller that knows why it's asking.
export const setHunting = (
  kind: SlotFactorKind,
  key: number,
  hunting: boolean
): WatchedSpark[] => update(kind, key, (e) => ({ ...e, hunting }));

// Whole set at once rather than add/remove pairs — the caller has the row's
// groups in hand from groupsOf, and a partial API would need the same dedupe
// twice. Duplicates collapse; an empty set drops the field entirely so an
// ungrouped row round-trips as the shape it started in.
export function setGroups(
  kind: SlotFactorKind,
  key: number,
  groups: string[]
): WatchedSpark[] {
  const next = [...new Set(groups)];
  return update(kind, key, (e) =>
    next.length > 0
      ? { ...e, groups: next }
      : { kind: e.kind, key: e.key, hunting: e.hunting }
  );
}

// For a caller that has to start from a known state — the e2e suite seeding a
// list, or a future import. Bypasses nothing: the same uniqueness rule
// applies.
export const replaceAll = (watched: WatchedSpark[]): WatchedSpark[] =>
  commit(dedupe(watched.filter(isEntry)));
